import NextAuthProvider from "@/providers/NextAuthProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ProfileProvider } from "@/providers/ProfileInfoProvider";
import { ApplicantsProvider } from "@/providers/ApplicantsProvider";
import { CreateJobProvider } from "@/providers/CreateJobProvider";

import "./globals.css";
import { AllJobsProvider } from "@/providers/AllJobsProvider";
import { AllCompaniesProvider } from "@/providers/AllCompaniesProvider";
import { PackagesProvider } from "@/providers/PackagesProvider";
import ScrollToTop from "./components/ScrollToTop";
import LayoutWrapper from "./components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollToTop />
        <NextAuthProvider>
          <ProfileProvider>
            <ApplicantsProvider>
              <AllCompaniesProvider>
                <AllJobsProvider>
                  <CreateJobProvider>
                    <PackagesProvider>
                      <LayoutWrapper>{children}</LayoutWrapper>
                    </PackagesProvider>
                  </CreateJobProvider>
                </AllJobsProvider>
              </AllCompaniesProvider>
            </ApplicantsProvider>
          </ProfileProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
