export const skillsList = [
  "ADP",
  "Amazon Seller Central",
  "BambooHR",
  "Client Relationship Management",
  "Data Visualization",
  "Data Warehousing",
  "Editing",
  "Email Campaigns",
  "Excel Modeling",
  "Financial Advisory",
  "Looker",
  "Market Research",
  "Prototyping",
  "Relationship Building",
  "Risk Management",
  "SEO",
  "Stakeholder Communication",
  "Wealth Management",
  "3D Animation",
  "3D Modeling",
  "A/B Testing",
  "Accounting",
  "Ad Design",
  "Admin",
  "Adobe After Affects",
  "Adobe Creative Suite",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Lightroom",
  "Adobe Photoshop",
  "Adobe Premiere",
  "Adobe XD",
  "AdWords",
  "Agile",
  "Agile Methodologies",
  "Agile/Scrum",
  "Ahrefs",
  "AI Consulting",
  "AI Content Creation",
  "AI Ethics and Responsible AI",
  "AI Governance",
  "AI Product Development",
  "AI Research",
  "AI Strategy",
  "AI Text-to-Speech",
  "AJAX",
  "Alpine.js",
  "Amazon",
  "Amazon ECS",
  "Analytics",
  "Analytics Tools",
  "Android",
  "AngularJS",
  "Animation",
  "Apache",
  "API",
  "API Development",
  "API Integration",
  "App Store Optimization",
  "Application Installations",
  "Architect",
  "Architecture",
  "Artificial Intelligence (AI)",
  "Audio Editing",
  "Automation Scripting",
  "AWS",
  "Azure",
  "Azure OpenAI",
  "Babel",
  "Backbone.js",
  "Backend",
  "Backlink Strategy",
  "Bamboo",
  "BambooHR",
  "Bard",
  "Bash",
  "Behavior Change Coaching",
  "BERT",
  "BigQuery",
  "Blockchain",
  "Blog Writing",
  "Bookkeeping",
  "Bootstrap",
  "Branding",
  "Budget Management",
  "Budgeting",
  "Buffer",
  "Bug Tracking",
  "Bulma",
  "Business Valuation",
  "BuzzSumo",
  "C",
  "C#",
  "C++",
  "Cache",
  "Canva",
  "Case Management",
  "Cassandra",
  "Celery",
  "Chai",
  "Character Design",
  "Chatbots",
  "ChatGPT",
  "CI/CD Pipelines",
  "Cisco Systems",
  "Client Relations",
  "Client Retention",
  "Client Retention Strategies",
  "Clojure",
  "Cloud",
  "Cloud Forensics",
  "CMS",
  "Cold Calling",
  "Color Theory",
  "Communication Skills",
  "Community Growth",
  "Competitor Analysis",
  "Compliance",
  "Composition",
  "Computer Vision",
  "Configuration Management",
  "Conflict Resolution",
  "Consumer Behavior",
  "Containers",
  "Content Creation",
  "Content Planning",
  "Content Strategy",
  "Content Writing",
  "Continuous Integration",
  "Continuous Integration Servers",
  "Contract Drafting",
  "Contract Negotiation",
  "Convolutional Neural Network (CNN)",
  "Copywriting",
  "Corporate Law",
  "Corporate Tax",
  "Corporate Wellness Programs",
  "CRM",
  "CRM Integration",
  "CRM Systems",
  "Cross-Browser Development",
  "Cross-Selling",
  "Cryptocurrency",
  "CSS",
  "CSS Preprocessors",
  "Customer Relationship Management",
  "Customer Service",
  "Customer Support",
  "Cyber Security",
  "Cypress",
  "Dart",
  "Dashboard Creation",
  "Data",
  "Data Analysis",
  "Data Cleaning",
  "Data Engineering",
  "Data Entry",
  "Data Mining",
  "Data Preprocessing"
]