"use client";
import { usePublicCV } from "@/providers/PublicCvProvider";
import Image from "next/image";
import { motion } from "framer-motion";

const PublicCv = () => {
  const { cv, loading } = usePublicCV();

  if (loading) {
    return (
      <div className="min-h-screen bg-white/[0.99] flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  if (!cv) {
    return (
      <div className="min-h-screen bg-white/[0.99] flex items-center justify-center">
        <p className="text-gray-900">CV not found</p>
      </div>
    );
  }

  const {
    summary,
    skills,
    hobbies,
    experience,
    projects,
    educations,
    certificates,
    courses,
    socials,
    companyName,
    languages,
    showPersonalInfo,
    showCompanyInfo,
    firstName,
    lastName,
    email,
    phone,
    companyLogo,
    primaryColor,
  } = cv;
  return (
    <div className="min-h-screen bg-white/[0.99] text-white py-5">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="fixed bottom-8 right-8 z-50 flex flex-col items-end gap-4"
      >
        <div className="bg-white/10 backdrop-blur-lg p-2 rounded-2xl shadow-xl border border-white/20">
          <button
            // onClick={() => window.print()}
            className="group flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-500 to-orange-600 rounded-xl hover:shadow-orange-500/25 hover:scale-105 transition-all duration-200"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-5 h-5 group-hover:scale-110 transition-transform"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
              />
            </svg>
            <span className="font-medium">Download PDF</span>
          </button>
        </div>

        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white/10 backdrop-blur-lg px-4 py-2 rounded-xl shadow-xl border border-white/20 text-sm text-black/80"
        >
          Generated by Arrow Agency
        </motion.div>
      </motion.div>
      <div className="max-w-screen-lg mx-auto px-4 xl:flex xl:space-x-5 space-y-8 xl:space-y-0">
        <div className="w-full min-h-[29.7cm] p-10 mx-auto  rounded-lg font-['Inter'] relative">
          {" "}
          {/* Add watermark */}
          <div className="absolute justify-center w-full h-full flex items-center top-0 left-0 gap-2 text-black/30 opacity-20 text-5xl">
            <span className="[writing-mode:vertical-rl] rotate-180 tracking-[10px]">
              Powered by Arrow Agency
            </span>
          </div>
          <div className="w-full min-h-[29.7cm] p-10 mx-auto bg-white shadow-md shadow-black/50 rounded-lg font-['Inter']">
            {/* Header Section */}
            <div className="mb-12">
              {showCompanyInfo ? (
                <div className="flex items-center gap-6 pb-6 border-b border-gray-200">
                  {companyLogo && companyLogo.url && (
                    <Image
                      src={companyLogo.url}
                      alt="Company Logo"
                      className="w-16 h-16 rounded-lg bg-white p-2"
                      width={companyLogo.width}
                      height={companyLogo.height}
                    />
                  )}
                  <h2 className="text-xl font-semibold text-gray-900">
                    {companyName}
                  </h2>
                </div>
              ) : (
                ""
              )}

              {showPersonalInfo ? (
                <div className="mt-6 flex flex-col gap-2">
                  <h1 className="text-2xl font-semibold text-gray-900">
                    {firstName} {lastName}
                  </h1>
                  <div
                    className="flex items-center gap-4"
                    style={{ color: primaryColor }}
                  >
                    {email !== "null" && email && (
                      <span className="flex items-center gap-2">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-4 h-4"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={1.5}
                            d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                          />
                        </svg>
                        {email}
                      </span>
                    )}
                    {phone !== "null" && phone && (
                      <span className="flex items-center gap-2">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-4 h-4"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={1.5}
                            d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                          />
                        </svg>
                        {phone}
                      </span>
                    )}
                  </div>
                </div>
              ) : (
                ""
              )}
            </div>

            <div className="grid grid-cols-[2.5fr,1fr] gap-12">
              {/* Main Content */}
              <div className="space-y-10">
                {summary && (
                  <section>
                    <p className="text-gray-600 leading-relaxed">{summary}</p>
                  </section>
                )}

                {experience?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Work Experience
                    </h2>
                    <div className="space-y-7">
                      {experience.map((exp, index) => (
                        <div key={index} className="relative">
                          <div className="flex flex-col gap-1.5 mb-3">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {exp.position}
                            </h3>
                            <p className="text-gray-600">{exp.company}</p>
                            <span className="text-xs text-gray-400 font-medium">
                              {exp.startDate ? exp.startDate : ""}
                              {exp.startDate && " - "}
                              {exp.endDate ? exp.endDate : "Present"}
                            </span>
                          </div>
                          <p className="text-gray-600 leading-relaxed">
                            {exp.description}
                          </p>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {educations?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Education
                    </h2>
                    <div className="space-y-6">
                      {educations.map((edu, index) => (
                        <div key={index} className="relative">
                          <div className="flex flex-col gap-1.5">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {edu.degree} in {edu.field}
                            </h3>
                            <p className="text-gray-600">{edu.institution}</p>
                            <span className="text-xs text-gray-400 font-medium">
                              {edu.startDate ? edu.startDate : ""}
                              {edu.startDate && " - "}
                              {edu.endDate ? edu.endDate : "Present"}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {projects?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Projects
                    </h2>
                    <div className="space-y-6">
                      {projects.map((project, index) => (
                        <div key={index} className="relative">
                          <div className="flex flex-col gap-1.5">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {project.name}
                            </h3>
                            <p className="text-gray-600">
                              {project.description}
                            </p>
                            {project.url && (
                              <a
                                href={project.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-sm hover:opacity-80 transition-opacity"
                                style={{ color: primaryColor }}
                              >
                                {project.url}
                              </a>
                            )}
                            <span className="text-xs text-gray-400 font-medium">
                              {project.startDate ? project.startDate : ""}
                              {project.startDate && " - "}
                              {project.endDate ? project.endDate : "Present"}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {courses?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Courses
                    </h2>
                    <div className="space-y-6">
                      {courses.map((course, index) => (
                        <div key={index} className="relative">
                          <div className="flex flex-col gap-1.5">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {course.name}
                            </h3>
                            {course.url && (
                              <a
                                href={course.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-sm hover:opacity-80 transition-opacity"
                                style={{ color: primaryColor }}
                              >
                                View Course →
                              </a>
                            )}
                            <span className="text-xs text-gray-400 font-medium">
                              {course.startDate ? course.startDate : ""}
                              {course.startDate && " - "}
                              {course.endDate ? course.endDate : "Present"}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {certificates?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Certificates
                    </h2>
                    <div className="space-y-6">
                      {certificates.map((cert, index) => (
                        <div key={index} className="relative">
                          <div className="flex flex-col gap-1.5">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {cert.name}
                            </h3>
                            <p className="text-gray-600">{cert.issuer}</p>
                            {cert.url && (
                              <a
                                href={cert.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-sm hover:opacity-80 transition-opacity"
                                style={{ color: primaryColor }}
                              >
                                View Certificate →
                              </a>
                            )}
                            <span className="text-xs text-gray-400 font-medium">
                              {cert.issueDate && cert.issueDate}
                              {cert.issueDate && " - "}
                              {cert.expirationDate && cert.expirationDate}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </section>
                )}
              </div>

              {/* Sidebar */}
              <div className="space-y-10">
                {skills?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Skills
                    </h2>
                    <div className="space-y-3">
                      {skills.map((skill, index) => (
                        <div
                          key={index}
                          className="flex justify-between items-center py-3 border-b border-gray-200 last:border-none"
                        >
                          <span className="text-gray-900">{skill.name}</span>
                          <span className="text-sm text-gray-500 font-medium">
                            {skill.efficiency}
                          </span>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {languages?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Languages
                    </h2>
                    <div className="space-y-3">
                      {languages.map((lang, index) => (
                        <div
                          key={index}
                          className="flex justify-between items-center py-3 border-b border-gray-200 last:border-none"
                        >
                          <span className="text-gray-900">{lang.name}</span>
                          <span className="text-sm text-gray-500 font-medium">
                            {lang.efficiency}
                          </span>
                        </div>
                      ))}
                    </div>
                  </section>
                )}

                {socials?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Social Links
                    </h2>
                    <div className="space-y-3">
                      {socials.map((social) => (
                        <a
                          key={social.id}
                          href={
                            social.url.startsWith("http")
                              ? social.url
                              : `https://${social.url}`
                          }
                          target="_blank"
                          rel="noopener noreferrer"
                          className="hover:opacity-80 block transition-opacity"
                          style={{ color: primaryColor }}
                        >
                          {social.name}
                        </a>
                      ))}
                    </div>
                  </section>
                )}

                {hobbies?.length > 0 && (
                  <section>
                    <h2
                      style={{ color: primaryColor }}
                      className="text-xs font-semibold  uppercase tracking-wider mb-6 pb-3 border-b border-gray-200"
                    >
                      Hobbies
                    </h2>
                    <div className="space-y-2">
                      {hobbies.map((hobby, index) => (
                        <p key={index} className="text-gray-600">
                          {hobby}
                        </p>
                      ))}
                    </div>
                  </section>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default PublicCv;
